### PR TITLE
Unlock goo-net dependancy

### LINKED ISSUE #35: locked to old version of gloo-net = "0.1.0"
This in turn causes other problems, because goo-net 0.1.0 requires the deprecated serde-serialize feature of wasm-bindgen, which in turn is known to produce dependency build loops.

* serde-serialize feature is deprecated, see https://github.com/rustwasm/wasm-bindgen/pull/3031.
* this causes circular dependencies, see https://github.com/rust-random/getrandom/issues/231

### PR DESCRIPTION
**Pull request by brianmay**
Fixes #35

### CODE REVIEW

**Comment by brianmay** [comment]
That seems to fix the build errors. Still testing.

**Comment by brianmay** [comment]
Confirmed that that appears to be working fine.

**Comment by ranile** [comment]
Thanks!

**Comment by ranile** [comment]
Cargo doesn't let me publish `*` dependencies. This also has the tendency of breaking downstream users because they don't get to choose what "major" (0.x) version of gloo-net they choose. I'll leave this commit in git though, so it's clear that no specific version of gloo is depended upon

**Pull request merged**
